version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - farmally
  nginx-redirect:
    image: nginx
    volumes:
      - ./nginx-redirect:/etc/nginx/conf.d
  farmally:
    build: .
    command: /bin/sh -c "rm -f /farmally/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/farmally
      - bundle_install:/usr/local/bundle
    links:
      - db
    environment:
      - EDITOR=vim
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_DATABASE=farmally
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data:
    driver: local
  bundle_install:
    driver: local
