version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - farmally
  nginx-redirect:
    image: nginx
    volumes:
      - ./nginx-redirect:/etc/nginx/conf.d
  farmally:
    build: .
    command: ./bin/rails s  
    volumes:
      - .:/farmally
    ports:
      - "3000:3000"
