version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Run test
          command: ./bin/rails test

  # Dockerfile of the image is here. https://github.com/tmyjoe/circleci-docker/tree/master/ruby-docker
  deploy:
    docker:
      - image: tmyjoe/circleci-ruby-docker
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: Publish docker image
          command: ./bin/packaging.sh
      - run:
          name: Packaging eb artifact
          command: ./bin/packaging.sh
      - run:
          name: Deploy to prod 
          command: ./bin/deploy.sh

workflows:
  version: 2
  dev_ops:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
