slack:
  icon_emoji: ':evergreen_tree:'
  username: ファーマリー
sitemap:
  bucket: 'jp.farmally.sitemap-dev'
phone:
  contact: "0120-401-718"
  contact_tractor: "0120-963-077"
site:
  name: "中古農機具販売サービス【ファーマリー】by DMM.com"